apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: custom-dish
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /data
