apiVersion: v1
kind: Secret
metadata:
  name: custom-dish-secret
  namespace: custom-dish
type: Opaque
data:
  access_token:  RE9maTA3QUJGRjNxano5c1NJN0lyR2I2bVQ0RjFJZGlHbEw0RGc3b0ZPUzB2dUVTU3I3cVlHc0JzREFWbEw1a2hn

